# Generated by Django 3.1.2 on 2020-10-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201025_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
