# Generated by Django 3.1.2 on 2020-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('type_of_user', models.CharField(default='Author', max_length=10)),
            ],
        ),
    ]
