SUCCESS="success"
FAILURE="failure"
INVALID_MOBILE_NUMBER = "Invalid mobile number"
INVALID_PASSWORD = "Invalid password combination. It should have atleast 8 letter, 1 uppercase, 1 lowercase"
INVALID_PINCODE = "Invalid Pincode"
USER_ADMIN = "Admin"
USER_AUTHOR = "Author"
INVALID_USER_TYPE = "Invalid user type"